package com.witty.securevault.ui.components

import com.witty.securevault.R

object LogoMapper {
    private val logoMap = mapOf(
        "netflix" to R.drawable.logo_netflix,
        "prime video" to R.drawable.logo_prime_video,
        "disney+ hotstar" to R.drawable.logo_disneyplus_hotstar,
        "jiohotstar" to R.drawable.logo_jiohotstar,
        "sony liv" to R.drawable.logo_sony_liv,
        "zee5" to R.drawable.logo_zee5,
        "jiocinema" to R.drawable.logo_jiocinema,
        "spotify" to R.drawable.logo_spotify,
        "apple music" to R.drawable.logo_apple_music,
        "youtube music" to R.drawable.logo_youtube_music,
        "gaana" to R.drawable.logo_gaana,
        "wynk music" to R.drawable.logo_wynk_music,
        "audible" to R.drawable.logo_audible,
        "kindle" to R.drawable.logo_kindle,
        "twitch" to R.drawable.logo_twitch,
        "crunchyroll" to R.drawable.logo_crunchyroll,
        "mx player" to R.drawable.logo_mx_player,
        "bookmyshow" to R.drawable.logo_bookmyshow,
        "imdb" to R.drawable.logo_imdb,
        "tata cliq" to R.drawable.logo_tata_cliq,
        "tata neu" to R.drawable.logo_tata_neu,
        "reliance digital" to R.drawable.logo_reliance_digital,
        "croma" to R.drawable.logo_croma,
        "decathlon" to R.drawable.logo_decathlon,
        "firstcry" to R.drawable.logo_firstcry,
        "lenskart" to R.drawable.logo_lenskart,
        "pepperfry" to R.drawable.logo_pepperfry,
        "urban company" to R.drawable.logo_urban_company,
        "cult.fit" to R.drawable.logo_cult_fit,
        "mamaearth" to R.drawable.logo_mamaearth,
        "boat" to R.drawable.logo_boat,
        "samsung" to R.drawable.logo_samsung,
        "xiaomi" to R.drawable.logo_xiaomi,
        "oneplus" to R.drawable.logo_oneplus,
        "realme" to R.drawable.logo_realme,
        "nothing" to R.drawable.logo_nothing,
        "domino's" to R.drawable.logo_dominos,
        "pizza hut" to R.drawable.logo_pizza_hut,
        "mcdonald's" to R.drawable.logo_mcdonalds,
        "kfc" to R.drawable.logo_kfc,
        "burger king" to R.drawable.logo_burger_king,
        "subway" to R.drawable.logo_subway,
        "starbucks" to R.drawable.logo_starbucks,
        "eatsure" to R.drawable.logo_eatsure,
        "freshmenu" to R.drawable.logo_freshmenu,
        "bigbasket" to R.drawable.logo_bigbasket,
        "jiomart" to R.drawable.logo_jiomart,
        "blinkit" to R.drawable.logo_blinkit,
        "zepto" to R.drawable.logo_zepto,
        "swiggy instamart" to R.drawable.logo_swiggy_instamart,
        "amazon fresh" to R.drawable.logo_amazon_fresh,
        "irctc" to R.drawable.logo_irctc,
        "indian railways" to R.drawable.logo_indian_railways,
        "redbus" to R.drawable.logo_redbus,
        "rapido" to R.drawable.logo_rapido,
        "uber" to R.drawable.logo_uber,
        "ola" to R.drawable.logo_ola,
        "airbnb" to R.drawable.logo_airbnb,
        "agoda" to R.drawable.logo_agoda,
        "cleartrip" to R.drawable.logo_cleartrip,
        "easemytrip" to R.drawable.logo_easemytrip,
        "ixigo" to R.drawable.logo_ixigo,
        "goibibo" to R.drawable.logo_goibibo,
        "yatra" to R.drawable.logo_yatra,
        "air india" to R.drawable.logo_air_india,
        "indigo" to R.drawable.logo_indigo,
        "akasa air" to R.drawable.logo_akasa_air,
        "uber eats" to R.drawable.logo_uber_eats,
        "indeed" to R.drawable.logo_indeed,
        "naukri" to R.drawable.logo_naukri,
        "internshala" to R.drawable.logo_internshala,
        "wellfound" to R.drawable.logo_wellfound,
        "glassdoor" to R.drawable.logo_glassdoor,
        "coursera" to R.drawable.logo_coursera,
        "udemy" to R.drawable.logo_udemy,
        "edx" to R.drawable.logo_edx,
        "skillshare" to R.drawable.logo_skillshare,
        "unacademy" to R.drawable.logo_unacademy,
        "physics wallah" to R.drawable.logo_physics_wallah,
        "byju's" to R.drawable.logo_byjus,
        "duolingo" to R.drawable.logo_duolingo,
        "steam" to R.drawable.logo_steam,
        "epic games" to R.drawable.logo_epic_games,
        "playstation" to R.drawable.logo_playstation,
        "xbox" to R.drawable.logo_xbox,
        "nintendo" to R.drawable.logo_nintendo,
        "riot games" to R.drawable.logo_riot_games,
        "ea" to R.drawable.logo_ea,
        "ubisoft" to R.drawable.logo_ubisoft,
        "battle.net" to R.drawable.logo_battle_net,
        "roblox" to R.drawable.logo_roblox,
        "minecraft" to R.drawable.logo_minecraft,
        "pubg" to R.drawable.logo_pubg,
        "bgmi" to R.drawable.logo_bgmi,
        "free fire" to R.drawable.logo_free_fire,
        "truecaller" to R.drawable.logo_truecaller,
        "jio" to R.drawable.logo_jio,
        "airtel" to R.drawable.logo_airtel,
        "vi" to R.drawable.logo_vi,
        "bsnl" to R.drawable.logo_bsnl,
        "tata play" to R.drawable.logo_tata_play,
        "paytm" to R.drawable.logo_paytm,
        "phonepe" to R.drawable.logo_phonepe,
        "cred" to R.drawable.logo_cred,
        "digilocker" to R.drawable.logo_digilocker,
        "umang" to R.drawable.logo_umang,
        "mygov" to R.drawable.logo_mygov,
        "uidai" to R.drawable.logo_uidai,
        "notion" to R.drawable.logo_notion,
        "canva" to R.drawable.logo_canva,
        "grammarly" to R.drawable.logo_grammarly,
        "dropbox" to R.drawable.logo_dropbox,
        "evernote" to R.drawable.logo_evernote,
        "adobe" to R.drawable.logo_adobe,
        "chatgpt" to R.drawable.logo_chatgpt,
        "perplexity" to R.drawable.logo_perplexity,
        "gemini" to R.drawable.logo_gemini,
        "claude" to R.drawable.logo_claude,
        "proton mail" to R.drawable.logo_proton_mail,
        "1password" to R.drawable.logo_1password,
        "bitwarden" to R.drawable.logo_bitwarden,
        "nordvpn" to R.drawable.logo_nordvpn,
        "instagram" to R.drawable.logo_instagram,
        "facebook" to R.drawable.logo_facebook,
        "x" to R.drawable.logo_x,
        "twitter" to R.drawable.logo_twitter,
        "snapchat" to R.drawable.logo_snapchat,
        "reddit" to R.drawable.logo_reddit,
        "linkedin" to R.drawable.logo_linkedin,
        "threads" to R.drawable.logo_threads,
        "discord" to R.drawable.logo_discord,
        "telegram" to R.drawable.logo_telegram,
        "whatsapp" to R.drawable.logo_whatsapp,
        "signal" to R.drawable.logo_signal,
        "pinterest" to R.drawable.logo_pinterest,
        "tiktok" to R.drawable.logo_tiktok,
        "tumblr" to R.drawable.logo_tumblr,
        "quora" to R.drawable.logo_quora,
        "medium" to R.drawable.logo_medium,
        "slack" to R.drawable.logo_slack,
        "microsoft teams" to R.drawable.logo_microsoft_teams,
        "zoom" to R.drawable.logo_zoom,
        "google" to R.drawable.logo_google,
        "gmail" to R.drawable.logo_gmail,
        "google drive" to R.drawable.logo_google_drive,
        "google photos" to R.drawable.logo_google_photos,
        "google cloud" to R.drawable.logo_google_cloud,
        "youtube" to R.drawable.logo_youtube,
        "google pay" to R.drawable.logo_google_pay,
        "microsoft" to R.drawable.logo_microsoft,
        "outlook" to R.drawable.logo_outlook,
        "onedrive" to R.drawable.logo_onedrive,
        "microsoft azure" to R.drawable.logo_microsoft_azure,
        "microsoft 365" to R.drawable.logo_microsoft_365,
        "github" to R.drawable.logo_github,
        "apple" to R.drawable.logo_apple,
        "icloud" to R.drawable.logo_icloud,
        "apple id" to R.drawable.logo_apple_id,
        "sbi" to R.drawable.logo_sbi,
        "hdfc bank" to R.drawable.logo_hdfc_bank,
        "icici bank" to R.drawable.logo_icici_bank,
        "axis bank" to R.drawable.logo_axis_bank,
        "kotak mahindra bank" to R.drawable.logo_kotak_mahindra_bank,
        "bank of baroda" to R.drawable.logo_bank_of_baroda,
        "punjab national bank" to R.drawable.logo_punjab_national_bank,
        "canara bank" to R.drawable.logo_canara_bank,
        "union bank" to R.drawable.logo_union_bank,
        "idfc first bank" to R.drawable.logo_idfc_first_bank,
        "indusind bank" to R.drawable.logo_indusind_bank,
        "yes bank" to R.drawable.logo_yes_bank,
        "federal bank" to R.drawable.logo_federal_bank,
        "razorpay" to R.drawable.logo_razorpay,
        "paypal" to R.drawable.logo_paypal,
        "stripe" to R.drawable.logo_stripe,
        "wise" to R.drawable.logo_wise,
        "revolut" to R.drawable.logo_revolut,
        "groww" to R.drawable.logo_groww,
        "zerodha" to R.drawable.logo_zerodha,
        "upstox" to R.drawable.logo_upstox,
        "angel one" to R.drawable.logo_angel_one,
        "coindcx" to R.drawable.logo_coindcx,
        "coinbase" to R.drawable.logo_coinbase,
        "amazon" to R.drawable.logo_amazon,
        "flipkart" to R.drawable.logo_flipkart,
        "myntra" to R.drawable.logo_myntra,
        "meesho" to R.drawable.logo_meesho,
        "ajio" to R.drawable.logo_ajio,
        "nykaa" to R.drawable.logo_nykaa,
        "ebay" to R.drawable.logo_ebay,
        "walmart" to R.drawable.logo_walmart,
        "ikea" to R.drawable.logo_ikea,
        "swiggy" to R.drawable.logo_swiggy,
        "zomato" to R.drawable.logo_zomato,
        "makemytrip" to R.drawable.logo_makemytrip,
        "booking.com" to R.drawable.logo_booking_com,
        "expedia" to R.drawable.logo_expedia,
        "gitlab" to R.drawable.logo_gitlab,
        "bitbucket" to R.drawable.logo_bitbucket,
        "docker" to R.drawable.logo_docker,
        "npm" to R.drawable.logo_npm,
        "pypi" to R.drawable.logo_pypi,
        "vercel" to R.drawable.logo_vercel,
        "netlify" to R.drawable.logo_netlify,
        "render" to R.drawable.logo_render,
        "heroku" to R.drawable.logo_heroku,
        "aws" to R.drawable.logo_aws,
        "digitalocean" to R.drawable.logo_digitalocean,
        "cloudflare" to R.drawable.logo_cloudflare,
        "mongodb" to R.drawable.logo_mongodb,
        "firebase" to R.drawable.logo_firebase,
        "supabase" to R.drawable.logo_supabase,
        "postman" to R.drawable.logo_postman,
        "figma" to R.drawable.logo_figma,
    )

    fun getLogoRes(website: String): Int? {
        val key = website.lowercase().trim()
        // Exact match
        logoMap[key]?.let { return it }
        // Partial match
        for ((k, v) in logoMap) {
            if (key.contains(k) || k.contains(key)) return v
        }
        return null
    }
}
